### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/RPL#14]
Frequently accessed data like the leader board and user statistics can be cookied in order to inject significant amounts of impetus into application performance, with conditional checks to ensure that the versions of the cookie contents and the matchday value (process.env.DAY) on the server match.

**Comment by aneesh-neelam** [comment]
Hey, don't do crap like this. Cookies are supposed to have identifying and tracking information only.

**Comment by kashishbest** [comment]
Revert it :p
