### ISSUE TITLE
Perpetuity.

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/RPL#17]
Use [forever] (https://www.npmjs.com/package/forever) to enable automatic application restarts in the event of a crash.

**Comment by aneesh-neelam** [comment]
That's a dumb suggestion. Heroku automatically restarts accordingly. Check this out: https://devcenter.heroku.com/articles/dynos#restarting

**Comment by kunagpal** [comment]
Of course it does, but forever circumnavigates the whole delay factor altogether.

**Comment by aneesh-neelam** [comment]
What delay factor? Heroku delays when there are repetitive crashes, in which case you should fix it first.

**Comment by kunagpal** [comment]
And have all the remaining users stuck by application down time while they wait for a fix?
