### ISSUE TITLE
Forgot Username or Password

### ISSUE THREAD

**Issue by aneesh-neelam** [IEEECS-VIT/RPL#2]
We left out this feature in GPL. We need to implement this in RPL though, no more excuses. 

Integrate with [Gmail's SMTP](https://mail.google.com/) or a service like [Sendgrid](http://sendgrid.com/) to send email with username. 

For password, since it is being hashed, a new password reset link must be generated and sent over email.

**Comment by kunagpal** [comment]
The feature was implemented ages ago, albeit for passwords only. Testing remains.
